### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by ayacoo** [Buddenbrock/typo3-icons#1]
At first: Thanks for your repo and work! :-)

I've got a "feature request": Grid 75-25 and Grid 25-75. This should then cover the most common grids.

Greets,
Guido

**Comment by Buddenbrock** [comment]
Thanks for your idea. At this time you can use the icons grid-40-60 and grid-60-40 for that, the sizes are nearly the same. In a future version I will add additionally icons for these grid combinations

**Comment by Buddenbrock** [comment]
I just released a new version faster than expected. This already includes your suggestion. So from version 0.1.2 you can use the  icons grid-75-25 and grid-25-70.

**Comment by ayacoo** [comment]
Thank you!
